### ISSUE TITLE
File contents in bounty screen

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/bounty-management#18]
It looks like the contents of files are used as the entries in the file list on the bounty details page, is this behavior correct? Filename or IPFS hash seems more intuitive to me.

**Comment by Rizato** [comment]
Oh. I see what you are saying now.

**Comment by Rizato** [comment]
I was using a lot of foo/foo and bar/bar files. Have to make some new files for bounties.

**Comment by Rizato** [comment]
Fixed in 1cb41f36d705e2839ac821fd55c791c6e3710d02 in master
Fixed in 98661da93ec2fc96474ca505fe2b746810c75dae in release-alpha
